#!/usr/bin/env python3
"""Extract Markdown fenced code blocks for TXT and LaTeX appendix delivery.

Usage:
    python extract_code_blocks.py <source.md> <output-directory>
"""
from __future__ import annotations

import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path


EXTENSIONS = {
    "bash": ".sh",
    "c": ".c",
    "cpp": ".cpp",
    "csharp": ".cs",
    "css": ".css",
    "html": ".html",
    "java": ".java",
    "javascript": ".js",
    "js": ".js",
    "json": ".json",
    "julia": ".jl",
    "latex": ".tex",
    "matlab": ".m",
    "mermaid": ".mmd",
    "powershell": ".ps1",
    "pseudocode": ".txt",
    "python": ".py",
    "r": ".R",
    "rust": ".rs",
    "shell": ".sh",
    "sql": ".sql",
    "text": ".txt",
    "typescript": ".ts",
    "ts": ".ts",
    "yaml": ".yaml",
}


@dataclass(frozen=True)
class CodeBlock:
    index: int
    language: str
    title: str
    content: str
    source_line: int
    extension: str


def _parse_info(info: str, index: int) -> tuple[str, str, str]:
    try:
        tokens = shlex.split(info.strip())
    except ValueError:
        tokens = info.strip().split()

    language = "text"
    metadata: dict[str, str] = {}
    if tokens and "=" not in tokens[0]:
        language = tokens.pop(0).strip().lower() or "text"
    for token in tokens:
        if "=" in token:
            key, value = token.split("=", 1)
            metadata[key.strip().lower()] = value.strip()

    supplied_title = metadata.get("title") or metadata.get("filename") or metadata.get("file")
    extension = EXTENSIONS.get(language, ".txt")
    title = Path(supplied_title).name if supplied_title else f"code-block-{index:03d}{extension}"
    return language, title, extension


def extract_fenced_code_blocks(markdown: str) -> list[CodeBlock]:
    lines = markdown.splitlines(keepends=True)
    blocks: list[CodeBlock] = []
    opening = re.compile(r"^ {0,3}(`{3,}|~{3,})([^\r\n]*)\r?\n?$")
    index = 0
    line_no = 0

    while line_no < len(lines):
        match = opening.match(lines[line_no])
        if not match:
            line_no += 1
            continue

        fence = match.group(1)
        info = match.group(2)
        closing = re.compile(
            rf"^ {{0,3}}{re.escape(fence[0])}{{{len(fence)},}}\s*\r?\n?$"
        )
        end = line_no + 1
        while end < len(lines) and not closing.match(lines[end]):
            end += 1
        if end >= len(lines):
            raise ValueError(f"Unclosed fenced code block beginning at line {line_no + 1}")

        index += 1
        language, title, extension = _parse_info(info, index)
        blocks.append(
            CodeBlock(
                index=index,
                language=language,
                title=title,
                content="".join(lines[line_no + 1 : end]),
                source_line=line_no + 1,
                extension=extension,
            )
        )
        line_no = end + 1

    return blocks


def _latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def write_outputs(blocks: list[CodeBlock], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    code_dir = output_dir / "code"
    code_dir.mkdir(parents=True, exist_ok=True)

    for stale in code_dir.iterdir():
        if stale.is_file() and re.fullmatch(r"\d{3}\.[A-Za-z0-9]+", stale.name):
            stale.unlink()

    txt_parts: list[str] = []
    tex_parts = ["% Generated by extract_code_blocks.py; do not edit manually.\n"]
    if blocks:
        tex_parts.extend(["\\clearpage\n", "\\section*{附录：源代码}\n"])

    for block in blocks:
        generated_name = f"{block.index:03d}{block.extension}"
        generated_path = code_dir / generated_name
        generated_path.write_text(block.content, encoding="utf-8", newline="")

        txt_parts.extend(
            [
                f"===== CODE BLOCK {block.index:03d} =====\n",
                f"language: {block.language}\n",
                f"title: {block.title}\n",
                f"source-line: {block.source_line}\n",
                f"file: code/{generated_name}\n",
                "===== BEGIN CODE =====\n",
                block.content,
            ]
        )
        if block.content and not block.content.endswith(("\n", "\r")):
            txt_parts.append("\n")
        txt_parts.append("===== END CODE =====\n\n")

        heading = _latex_escape(f"代码 {block.index}：{block.title}")
        language = _latex_escape(block.language)
        tex_parts.extend(
            [
                f"\\subsection*{{{heading}}}\n",
                f"\\noindent\\textbf{{语言：}}{language}\\par\n",
                "\\VerbatimInput[breaklines=true,breakanywhere=true,"
                "numbers=left,numbersep=6pt,fontsize=\\small,frame=single,"
                f"framesep=3mm]{{code/{generated_name}}}\n",
            ]
        )

    (output_dir / "source-code.txt").write_text(
        "".join(txt_parts), encoding="utf-8", newline=""
    )
    (output_dir / "code-appendix.tex").write_text(
        "".join(tex_parts), encoding="utf-8", newline=""
    )


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: python extract_code_blocks.py <source.md> <output-directory>")
        return 2

    source = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])
    try:
        markdown = source.read_text(encoding="utf-8")
        blocks = extract_fenced_code_blocks(markdown)
        write_outputs(blocks, output_dir)
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1

    print(f"Extracted {len(blocks)} fenced code block(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
